### ISSUE TITLE
What is ScissorPush and where is it?

### ISSUE THREAD

**Issue by AndersHogqvist** [Kovak/FlatKivy#2]
I was looking forward on give FlatKivy a try since it looks really awesome. However, I get an ImportError on ScissorPush. I can't find this module anywhere and googling does't give me any clues. Kivy source doesn't have this module as far as I can tell. So, how do I find it?

**Comment by AndersHogqvist** [comment]
Found it

**Comment by ialvarez** [comment]
Hey, I have the same issue, could you share how you fixed it? Thanks!

**Comment by mrhubbs** [comment]
ScissorPush is a graphics instruction in Kivy 1.9.1.  FlatKivy no longer requires ScissorPush, so you can use Kivy 1.9.
